# TODO: try to restrict on which nodes it gets schedule (cannot be deployed as a Deployment because of too many ports) with nodeSelector
controllerType: DaemonSet
containers:
  - name: rtpproxy
    image: lineblocs/rtpproxy:master
    resources:
      requests:
        cpu: "10m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "2048Mi"
envs:
  configs:
    OPENSIPS_HOST: <opensips_url/ip>
