apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: {{ default "nginx" .Values.ingressClassName }}
    {{- with .Values.certs.issuerName }}
    cert-manager.io/cluster-issuer: {{ . }}
    default-ssl-certificate: {{ . }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    ingress.kubernetes.io/proxy-body-size: "128m"
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "128m"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
    {{- if .Values.tls.force }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    {{- with .Values.annotations }}
    {{ . | toYaml | indent 4 | trim }}
    {{- end }}
spec:
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.deploymentDomain }}
        - app.{{ .Values.deploymentDomain }}
        - editor.{{ .Values.deploymentDomain }}
        - phpmyadmin.{{ .Values.deploymentDomain }}
        - internals.{{ .Values.deploymentDomain }}
        - prv.{{ .Values.deploymentDomain }}
        - tsc.{{ .Values.deploymentDomain }}
      secretName: {{ .Values.certs.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-com
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: app.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-app
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: editor.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-editor
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: phpmyadmin.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: phpmyadmin-service
                port:
                  number: {{ .Values.ports }}
            path: /
            pathType: Prefix
    - host: internals.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-internals
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: prv.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-prv
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: tsc.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-tsc-compiler
                port:
                  number: 80
            path: /
            pathType: Prefix