apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: {{ default "nginx" .Values.ingressClassName }}
    {{- with .Values.certs.issuerName }}
    cert-manager.io/cluster-issuer: {{ . }}
    default-ssl-certificate: {{ . }}
    {{- end }}
    {{- if .Values.tls.force }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    {{- with .Values.annotations }}
    {{ . | toYaml | indent 4 | trim }}
    {{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingressClassName }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.deploymentDomain }}
        - app.{{ .Values.deploymentDomain }}
        - editor.{{ .Values.deploymentDomain }}
        - phpmyadmin.{{ .Values.deploymentDomain }}
        - internals.{{ .Values.deploymentDomain }}
        - prv.{{ .Values.deploymentDomain }}
        - tsc.{{ .Values.deploymentDomain }}
      secretName: {{ .Values.certs.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-com
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: app.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-app
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: editor.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-editor
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: phpmyadmin.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-phpmyadmin
                port:
                  number: {{ .Values.ports }}
            path: /
            pathType: Prefix
    - host: internals.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-internals
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: prv.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-prv
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: tsc.{{ .Values.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.webChartReleaseName }}-tscbindings
                port:
                  number: 80
            path: /
            pathType: Prefix