apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opensips
  labels:
    component: opensips
spec:
  selector:
    matchLabels:
      component: opensips
  template:
    metadata:
      name: opensips
      labels:
        component: opensips
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rtpproxy
          image: lineblocs/rtpproxy:master
        - name: opensips
          image: lineblocs/opensips-proxy:master
          resources:
            requests:
              cpu: "100m"
              memory: "1024Mi"
            limits:
              cpu: "300m"
              memory: "2048Mi"
          env:
            - name: DB_HOST
              value: 104.248.107.119
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "4ChTXGuEUtrj6b4H"
            - name: DB_NAME
              value: opensips
            - name: RTPPROXY_IPV4
              value: 127.0.0.1
            - name: LINEBLOCS_KEY
              value: CONFIGURED_LINEBLOCS_KEY
            - name: DEPLOYMENT_DOMAIN
              value: CONFIGURED_DEPLOYMENT_DOMAIN