apiVersion: v1
kind: Service
metadata:
  name: grpc-processor
  labels:
    component: grpc
spec:
  selector:
    component: grpc
  ports:
  - name: websocket
    port: 8017
  - name: grpc
    port: 9001
