apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: com-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Max
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment 
    name: lineblocs-com