apiVersion: batch/v1
kind: CronJob
metadata:
  name: lineblocs-cron-monthly
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: AWS_ACCESS_KEY_ID
              value: AKIAJHVI2B5KLCRD3BIQ
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: MAILGUN_DOMAIN
              value: email.lineblocs.com
            - name: MAILGUN_API_KEY
              value: XXX
            - name: STRIPE_KEY
              value: sk_live_XyRu0OIhRnlKjf3BvyHecpqy
            name: monthlybill
            image: lineblocs/crontabs:master
            args:
              - /bin/bash
              - -c
              - cd /app/ && ./main.go monthly
          restartPolicy: OnFailure