apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtpproxy
  namespace: lineblocs
  labels:
    component: rtpproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      component: rtpproxy
  template:
    metadata:
      labels:
        component: rtpproxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - rtpproxy
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: rtpproxy
          image: lineblocs/rtpproxy:master
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "2048Mi"
      #nodeSelector:
      #  mediaServerNode: 'true'
      tolerations:
      - key: dedicated
        operator: Equal
        value: experimental
        effect: NoSchedule