apiVersion: v1
kind: Service
metadata:
  name: lineblocs-internals
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 9999
    targetPort: 9999
    name: tcp
  selector:
    app: lineblocs-internals