apiVersion: apps/v1
kind: Deployment
metadata:
  {{ include "resource.metadata" (dict "name" "asterisk" "context" .) }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "resource.matchLabels" (dict "name" "asterisk" "context" .) | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "resource.matchLabels" (dict "name" "asterisk" "context" .) | indent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - asterisk
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: asterisk
          image: lineblocs/asterisk:master
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "2048Mi"
          env:
            - name: ARI_PASSWORD
              value: GENERATED_ARI_PASSWORD
        - name: apps
          image: lineblocs/ari-apps:master
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: ARI_HOST
              value: {{ .Values.voip.ariHost }}
            - name: ARI_PORT
              value: {{ .Values.voip.ariPort | quote }}
            - name: ARI_USERNAME
              value: {{ .Values.voip.ariUser }}
            - name: ARI_PASSWORD
              value: {{ .Values.voip.ariPassword }}
            - name: ARI_USE_PROXY
              value: {{ .Values.voip.ariUseProxy | toString | quote }}
            - name: NATSGW_URL
              value: nats://{{ .Release.Name }}-nats:4222
            - name: DEPLOYMENT_DOMAIN
              value: {{ .Values.deploymentDomain }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/service.json"
            - name: LOG_LEVEL
              value: INFO
            - name: LINEBLOCS_KEY
              value: {{ .Values.lineblocsKey | quote }}
        - name: monitor
          image: lineblocs/media-monitor:master
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: DB_HOST
              value: {{ include "lineblocs.mysql.host" . }}
            - name: DB_USER
              value: root
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: {{ ternary (printf "%s-mysql" .Release.Name) (include "lineblocs.fullname" $) .Values.mysql.enabled }}
                  optional: false
            - name: DB_NAME
              value: {{ include "lineblocs.mysql.database" . }}
            - name: AMI_HOST
              value: {{ .Values.voip.amiHost }}
            - name: AMI_PORT
              value: {{ .Values.voip.amiPort | quote }}
            - name: AMI_USER
              value: {{ .Values.voip.amiUser }}
            - name: AMI_PASS
              value: {{ .Values.voip.amiPassword }}
            - name: NATSGW_URL
              value: nats://{{ .Release.Name }}-nats:4222
            - name: LOG_LEVEL
              value: INFO
            - name: LINEBLOCS_KEY
              value: {{ .Values.lineblocsKey | quote }}
            - name: LINEBLOCS_REGION
              value: ca-central-1
      #nodeSelector:
      #  mediaServerNode: 'true'
      tolerations:
      - key: dedicated
        operator: Equal
        value: experimental
        effect: NoSchedule