apiVersion: v1
kind: Service
metadata:
  {{- include "resource.metadata" (dict "name" "editor" "context" .) }}

spec:
  type: {{ default "ClusterIP" .Values.editor.service.type }}
  ports:
    - port: 80
      targetPort: 3000
  selector:
    {{- include "resource.matchLabels" (dict "name" "editor" "context" .) | indent 4 }}