apiVersion: v1
kind: Service
metadata:
  {{- include "resource.metadata" (dict "name" "app" "context" .) }}

spec:
  type: {{ default "ClusterIP" .Values.app.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    {{- include "resource.matchLabels" (dict "name" "app" "context" .) | indent 4 }}
