apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ include "lineblocs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lineblocs.chart" . }}

spec:
  acme:
    # Email address used for ACME registration
    email: {{ required "email required for letsencrypt usage" .Values.letsencryptEmail }}
    server: {{ default "https://acme-v02.api.letsencrypt.org/directory" .Values.letsencryptServer }}
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: {{ include "lineblocs.fullname" . }}-keys
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.ingressClassName }}