apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "resource.metadata" (dict "name" "com" "context" .) }}

spec:
  replicas: {{ .Values.com.replicas }}
  selector:
    matchLabels:
      {{- include "resource.matchLabels" (dict "name" "com" "context" .) | indent 6 }}

  template:
    metadata:
      labels:
        {{- include "resource.matchLabels" (dict "name" "com" "context" .) | indent 8 }}

    spec:
      containers:
        - name: {{ include "resource.name" (dict "name" "com" "context" .) }}
          {{- $repository := default "lineblocs/site" .Values.com.image.repository }}
          {{- $tag := default "master" .Values.com.image.tag }}
          image: {{ printf "%s:%s" $repository $tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.com.image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: X-Health
                  value: health
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              cpu: {{ default "64m" .Values.internalApi.resources.requests.cpu }}
              memory: {{ default "32Mi" .Values.internalApi.resources.requests.memory }}
            limits:
              cpu: {{ default "4096m" .Values.internalApi.resources.limit.cpu }}
              memory: {{ default "16384Mi" .Values.internalApi.resources.limit.memory }}
          env:
            - name: DEPLOYMENT_DOMAIN
              value: {{ .Values.deploymentDomain | quote }}
            {{- include "mysql.env" . | indent 12 }}
            - name: DB_OPENSIPS_DATABASE
              value: {{ .Values.opensipsDatabase | quote }}