apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineblocs-editor

spec:
  replicas: 1
  selector:
    matchLabels:
      app: lineblocs-editor

  template:
    metadata:
      labels:
        app: lineblocs-editor
    spec:
      containers:
      - name: lineblocs-editor
        image: lineblocs/flow-designer:master
        ports:
        - containerPort: 80
        env:
          - name: DEPLOYMENT_DOMAIN
            value: lineblocs-test.com