apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lineblocs.fullname" . }}-editor
  labels:
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lineblocs.chart" . }}

spec:
  replicas: {{ .Values.editor.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "lineblocs.name" . }}-editor

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "lineblocs.name" . }}-editor
    spec:
      containers:
        - name: lineblocs-editor
          image: {{ printf "%s:%s" .Values.editor.image.repository .Values.editor.image.tag }}
          # TODO
          ports:
            - containerPort: 80
          env:
            - name: DEPLOYMENT_DOMAIN
              value: {{ .Values.deploymentDomain }}