{{- if and (.Values.ingress) (.Values.ingress.enableDemo) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: {{ default "nginx" .Values.ingress.ingressClassName }}
    {{- with .Values.ingress.certs.issuerName }}
    cert-manager.io/cluster-issuer: {{ . }}
    default-ssl-certificate: {{ . }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    ingress.kubernetes.io/proxy-body-size: "128m"
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "128m"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
    {{- with .Values.ingress.annotations }}
    {{ . | toYaml | indent 4 | trim }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.deploymentDomain }}
        - app.{{ .Values.ingress.deploymentDomain }}
        - editor.{{ .Values.ingress.deploymentDomain }}
        - phpmyadmin.{{ .Values.ingress.deploymentDomain }}
        - internals.{{ .Values.ingress.deploymentDomain }}
        - prv.{{ .Values.ingress.deploymentDomain }}
        - tsc.{{ .Values.ingress.deploymentDomain }}
      secretName: {{ .Values.ingress.certs.secretName }}
  rules:
    - host: {{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: lineblocs-com
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: app.{{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: lineblocs-app
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: editor.{{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: lineblocs-editor
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: phpmyadmin.{{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: internals.{{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: lineblocs-internals
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: prv.{{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: lineblocs-prv
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: tsc.{{ .Values.ingress.deploymentDomain }}
      http:
        paths:
          - backend:
              service:
                name: lineblocs-tsc-compiler
                port:
                  number: 80
            path: /
            pathType: Prefix
  {{- end -}}