apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "resource.metadata" (dict "name" "" "context" .) }}
    {{- if or .Values.ingress.customAnnotations .Values.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ include "resource.name" (dict "name" "" "context" $) }}
    default-ssl-certificate: {{ include "resource.name" (dict "name" "" "context" $) }}
    {{- if .Values.ingress.customAnnotations }}
    {{- toYaml .Values.ingress.customAnnotations | indent 4 }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  {{- if default false .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range (include "lineblocs.ingress.hosts" . | splitList ", ") }}
        - {{ quote . }}
        {{- end }}
  {{- end }}
  rules: {{- include "lineblocs.ingress.rules" . | nindent 4 }}