apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "resource.metadata" (dict "name" "internals" "context" .) }}

spec:
  replicas: {{ .Values.internalApi.replicas }}
  selector:
    matchLabels:
      {{- include "resource.matchLabels" (dict "name" "internals" "context" .) | indent 6 }}

  template:
    metadata:
      labels:
        {{- include "resource.matchLabels" (dict "name" "internals" "context" .) | indent 8 }}
    spec:
      containers:
        - env:
            {{- include "mysql.env" . | indent 12 }}
            {{- include "etcd.env" . | indent 12 }}
            - name: USE_LIMIT_MIDDLEWARE
              value: {{ .Values.internalApi.useLimitMiddleware | quote }}
            - name: USE_TLS
              value: {{ .Values.internalApi.useTls | quote }}
          {{- if .Values.internalApi.extraEnv }}
            {{- toYaml .Values.internalApi.extraEnv | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              httpHeaders:
                - name: X-Health
                  value: health
            initialDelaySeconds: 3
            periodSeconds: 3
          name: {{ include "resource.name" (dict "name" "internals" "context" .) }}
          {{ $repository := default "lineblocs/internals-api" .Values.internalApi.image.repository }}
          {{ $tag := default "master" .Values.internalApi.image.tag }}
          image: {{ printf "%s:%s" $repository $tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.internalApi.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 9999
          resources:
            requests:
              cpu: {{ default "10m" .Values.internalApi.resources.requests.cpu }}
              memory: {{ default "128Mi" .Values.internalApi.resources.requests.memory }}
            limits:
              cpu: {{ default "300m" .Values.internalApi.resources.limit.cpu }}
              memory: {{ default "256Mi" .Values.internalApi.resources.limit.memory }}
