apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lineblocs.fullname" . }}-internals
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}
    helm.sh/chart: {{ include "lineblocs.chart" . }}

spec:
  replicas: {{ .Values.internalApi.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lineblocs.name" }}-internals
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "lineblocs.name" . }}-internals
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: {{ include "db.hostname" . }}
            - name: DB_USER
              value: {{ .Values.db.username }}
            - name: DB_PASS
              value: {{ .Values.db.password }}
            - name: DB_NAME
              value: {{ .Values.db.database }}
            - name: ETCD_ENDPOINT
              value: {{ include "lineblocs.etcd.host" . }}
            - name: ETCD_USERNAME
              value: root
            - name: ETCD_PASSWORD
              value: {{ .Values.etcd.auth.rbac.rootPassword }}
            - name: USE_LIMIT_MIDDLEWARE
              value: {{ .Values.internalApi.useLimitMiddleware | quote }}
            - name: USE_TLS
              value: {{ .Values.internalApi.useTls | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.internalApi.livenessProbe.path }}
              port: {{ .Values.internalApi.livenessProbe.port }}
              httpHeaders:
                - name: X-Health
                  value: health
            initialDelaySeconds: {{ .Values.internalApi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.internalApi.livenessProbe.periodSeconds }}
          name: lineblocs-internals
          image: {{ printf "%s:%s" .Values.internalApi.image.repository .Values.internalApi.image.tag }}
          imagePullPolicy: {{ .Values.internalApi.image.pullPolicy }}
          ports:
            {{- range .Values.internalApi.ports }}
            - containerPort: {{ . }}
            {{- end }}
          resources:
            requests:
              cpu: {{ default "10m" .Values.internalApi.resources.requests.cpu }}
              memory: {{ default "128Mi" .Values.internalApi.resources.requests.memory }}
            limits:
              cpu: {{ default "300m" .Values.internalApi.resources.limit.cpu }}
              memory: {{ default "256Mi" .Values.internalApi.resources.limit.memory }}