apiVersion: v1
kind: Service
metadata:
  name: {{ include "lineblocs.fullname" . }}-internal
  labels:
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}
    helm.sh/chart: {{ include "lineblocs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}

spec:
  type: {{ .Values.internalApi.service.type }}
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 9999
      targetPort: 9999
      name: tcp
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}-internals
