apiVersion: v1
kind: Service
metadata:
  {{- include "resource.metadata" (dict "name" "internals" "context" .) }}

spec:
  type: {{ default "ClusterIP" .Values.internalApi.service.type }}
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 9999
      targetPort: 9999
      name: tcp
  selector:
    {{- include "resource.matchLabels" (dict "name" "internals" "context" .) | indent 4 }}