apiVersion: apps/v1
kind: Deployment
metadata:
  {{ include "resource.metadata" (dict "name" "managers" "context" .) }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "resource.matchLabels" (dict "name" "managers" "context" .) | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "resource.matchLabels" (dict "name" "managers" "context" .) | indent 8 }}
    spec:
      containers:
        - name: {{ include "resource.name" (dict "name" "recording-manager" "context" .) }}
          image: lineblocs/recordings-mngr:master
          env:
            - name: DB_HOST
              value: CONFIGURED_DB_HOST
            - name: DB_USER
              value: CONFIGURED_DB_USER
            - name: DB_PASS
              value: CONFIGURED_DB_PASS
            - name: DB_NAME
              value: CONFIGURED_DB_NAME
            - name: ARI_HOST
              value: asterisk
            - name: ARI_PORT
              value: "8088"
            - name: ARI_USERNAME
              value: ariuser
            - name: ARI_PASSWORD
              value: GENERATED_ARI_PASSWORD
            - name: DEPLOYMENT_DOMAIN
              value: CONFIGURED_DEPLOYMENT_DOMAIN
            - name: LOG_LEVEL
              value: INFO
        - name: {{ include "resource.name" (dict "name" "billing-manager" "context" .) }}
          image: lineblocs/billing-mngr:master
          env:
            - name: DB_HOST
              value: CONFIGURED_DB_HOST
            - name: DB_USER
              value: CONFIGURED_DB_USER
            - name: DB_PASS
              value: CONFIGURED_DB_PASS
            - name: DB_NAME
              value: CONFIGURED_DB_NAME     
