apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{ include "resource.metadata" (dict "name" "opensips" "context" .) }}
spec:
  selector:
    matchLabels:
      {{- include "resource.matchLabels" (dict "name" "opensips" "context" .) | indent 6 }}
  template:
    metadata:
      name: {{ include "resource.name" (dict "name" "opensips" "context" .) }}
      labels:
        {{- include "resource.matchLabels" (dict "name" "opensips" "context" .) | indent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{ include "resource.name" (dict "name" "opensips" "context" .) }}
          image: lineblocs/opensips-proxy:master
          resources:
            requests:
              cpu: "100m"
              memory: "1024Mi"
            limits:
              cpu: "300m"
              memory: "2048Mi"
          env:
            - name: DB_HOST
              value: {{ include "lineblocs.mysql.host" . }}
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: {{ ternary (printf "%s-mysql" .Release.Name) (include "lineblocs.fullname" $) .Values.mysql.enabled }}
                  optional: false
            - name: DB_NAME
              value: {{ .Values.opensipsDatabase | quote }}
            - name: RTPPROXY_IPV4
              value: 127.0.0.1
            - name: LINEBLOCS_KEY
              value: {{ .Values.lineblocsKey | quote }}
            - name: DEPLOYMENT_DOMAIN
              value: {{ .Values.deploymentDomain | quote }}