apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "resource.metadata" (dict "name" "phpmyadmin" "context" .) }}

spec:
  replicas: 1
  selector:
    matchLabels: {{- include "resource.matchLabels" (dict "name" "phpmyadmin" "context" $) | nindent 6 }}

  template:
    metadata:
      labels: {{- include "resource.matchLabels" (dict "name" "phpmyadmin" "context" $) | nindent 6 }}

    spec:
      containers:
        - name: {{ include "resource.name" (dict "name" "phpmyadmin" "context" $) }}
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 8015
          env:
            - name: PMA_HOST
              value: {{ include "lineblocs.mysql.host" . }}
            - name: PMA_PORT
              value:  "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ ternary (printf "%s-mysql" .Release.Name) (include "lineblocs.fullname" $) .Values.mysql.enabled }}
                  key: mysql-root-password