# creates the users needed by the backend pods
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "lineblocs.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded

spec:
  restartPolicy: Never
  volumes:
    - name: scripts
      configMap:
        name: {{ include "lineblocs.fullname" . }}-scripts
        items:
          - key: create_users.sql
            path: create_users.sql
  containers:
    - name: {{ include "lineblocs.fullname" . }}-post-install
      image: percona
      env:
        - name: MYSQL_HOST
          value: {{ include "db.hostname" . }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: {{ .Release.Name }}-db
      volumeMounts:
        - mountPath: /tmp
          name: scripts
      command:
        - sh
        - -c
        - |
          # sleep a little while before trying
          sleep 30s
          mysql -h$MYSQL_HOST -uroot -p$MYSQL_PASSWORD < /tmp/create_users.sql

