apiVersion: v1
kind: Service
metadata:
  {{- include "resource.metadata" (dict "name" "routeEditor" "context" $) }}

spec:
  type: {{ default "ClusterIP" .Values.routeEditor.service.type }}
  ports:
    - port: 80
      targetPort: 8005
  selector:
    {{- include "resource.matchLabels" (dict "name" "routeEditor" "context" $) | indent 4}}