apiVersion: v1
kind: Service
metadata:
  name: {{ include "lineblocs.fullname" . }}-route-editor
  labels:
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lineblocs.chart" . }}

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8005
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}-route-editor