apiVersion: v1
kind: Service
metadata:
  name: {{ template "lineblocs.fullname" . }}-com
  labels:
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "lineblocs.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "lineblocs.name" . }}-com