apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "resource.metadata" (dict "name" "tsBinding" "context" .) }}

spec:
  replicas: {{ .Values.tsBinding.replicas }}
  selector:
    matchLabels:
      {{- include "resource.matchLabels" (dict "name" "tsBinding" "context" .) | indent 6 }}

  template:
    metadata:
      labels:
        {{- include "resource.matchLabels" (dict "name" "tsBinding" "context" .) | indent 8 }}
    spec:
      containers:
        - name: {{ include "resource.name" (dict "name" "tsBinding" "context" .) }}
          {{ $repository := default "lineblocs/ts-bindings" .Values.tsBinding.image.repository }}
          {{ $tag := default "master" .Values.tsBinding.image.tag }}
          image: {{ printf "%s:%s" $repository $tag }}
          ports:
            - containerPort: 8080