apiVersion: v1
kind: Service
metadata:
  {{- include "resource.metadata" (dict "name" "ts-binding" "context" .) }}

spec:
  type: {{ default "ClusterIP" .Values.tsBindings.service.type }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
    {{- include "resource.matchLabels" (dict "name" "ts-binding" "context" .) | indent 4 }}