{{/*Only creates this secret if neither of etc or mysql are chart-internal*/}}
{{- if not (and .Values.etcd.enabled .Values.mysql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "resource.metadata" (dict "name" "" "context" .) }}

data:
  {{- if not .Values.mysql.enabled }}
  mysql-password: {{ .Values.externalMysqlPassword | b64enc | quote }}
  mysql-root-password: {{ .Values.externalMysqlRootPassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.etcd.enabled }}
  etcd-root-password: {{ .Values.externalEtcdRootPassword }}
  {{- end }}
{{- end }}