issuer:
  name: letsencrypt-prod

web:
  service:
    port: 80
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: chart-example.local
        paths: []
    secretName: web-tls
    tls: []
    