kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-retain
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
  type: gp2