# voip services
apiVersion: v1
kind: Secret
metadata:
  name: ami-secret
type: Opaque
stringData:
  AMI_HOST: "127.0.0.1"
  AMI_PORT: "5038"
  AMI_USERNAME: "admin"
  AMI_PASSWORD: "<your_ami_password>"
---
apiVersion: v1
kind: Secret
metadata:
  name: ari-secret
type: Opaque
stringData:
  ARI_HOST: "127.0.0.1"
  ARI_PORT: "8088"
  ARI_USERNAME: "admin"
  ARI_PASSWORD: "<your_ari_password>"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: "<your-mysql-user>"
  DB_PASS: "<your-mysql-pass>"
  DB_NAME: "lineblocs"
  DB_OPENSIPS: "opensips"
  DB_HOMER: "homer_data"
  DB_HOST: "<your-mysql-host>"
---
apiVersion: v1
kind: Secret
metadata:
  name: lineblocs-secret
type: Opaque
stringData:
  LINEBLOCS_KEY: "<your-lineblocs-routing-key>"