# web services
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: "<your-mysql-user>"
  DB_PASS: "<your-mysql-pass>"
  DB_NAME: "lineblocs"
  DB_HOST: "<your-mysql-host>"
  DB_OPENSIPS_DATABASE: "opensips"
---
apiVersion: v1
kind: Secret
metadata:
  name: lineblocs-site
type: Opaque
stringData:
  DB_USER: "<your-mysql-user>"
  DB_PASS: "<your-mysql-pass>"
  DB_NAME: "lineblocs"
  DB_HOST: "<your-mysql-host>"
  DB_OPENSIPS_DATABASE: "opensips"
