apiVersion: v2
name: web
description: Lineblocs Web Helm Chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: cert-manager
    alias: certmanager
    version: v1.11.0
    repository: https://charts.jetstack.io
    condition: certmanager.enabled
      # TODO maybe include this later
  # - name: pxc-operator
  #   condition: perconaoperator.enabled
  #   version: 1.12.1
  #   repository: https://percona.github.io/percona-helm-charts
  #   alias: perconaoperator
  # - name: pxc-db
  #   condition: db.enabled
  #   version: 1.12.0
  #   repository: https://percona.github.io/percona-helm-charts
  #   alias: db
  - name: etcd
    repository: https://charts.bitnami.com/bitnami
    condition: etcd.enabled
    version: 8.x.x
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
    version: 9.x.x
