global:
  externalMysqlVersion: "5.7"
  envs:
    DEPLOYMENT_DOMAIN: lineblocs.com

# TODO: add tags for components

etcd:
  enabled: false

ingress:
  enableDemo: true
  deploymentDomain: lineblocs-test.site
  certs:
    issuerName: myac
    secretName: lineblocs-ingress-tls

app:
  containers:
    - name: app
      image: lineblocs/user-app:master
      ports:
        - containerPort: 8000
  domain: app.
  service:
    ports:
      - port: 80
        targetPort: 8000

com:
  containers:
    - name: site
      image: lineblocs/site:master
      imagePullPolicy: Always
      livenessProbe:
        httpGet:
          httpHeaders:
            - name: X-Health
              value: health
          path: /healthz
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "4096m"
          memory: "16384Mi"
        requests:
          cpu: "64m"
          memory: "32Mi"
      volumeMounts:
        - name: site
          mountPath: /var/www/html/storage/app/public
  domain: com.
  envs:
    configs:
      DB_OPENSIPS_DATABASE: opensips
    secrets:
      - db-secret
  pvc:
    - name: site
      size: 2Gi
  service:
    ports:
      - port: 80
        targetPort: 8080

editor:
  containers:
    - name: editor
      image: lineblocs/flow-designer:master
      ports:
        - containerPort: 80
  domain: editor.
  service:
    ports:
      - port: 80
        targetPort: 80

internals:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  containers:
    - name: lineblocs-internals
      image: lineblocs/internals-api:master
      ports:
        - containerPort: 80
        - containerPort: 9999
      resources:
        requests:
          cpu: "10m"
          memory: "128Mi"
        limits:
          cpu: "300m"
          memory: "256Mi"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
          httpHeaders:
            - name: X-Health
              value: health
        initialDelaySeconds: 20
        periodSeconds: 5
  envs:
    secrets:
      - db-secret
      - etcd-secret
    configs:
      USE_LIMIT_MIDDLEWARE: "off"
      USE_TLS: "off"
      USE_DOTENV: "off"
  service:
    ports:
      - port: 80
        targetPort: 80
        name: http
      - port: 9999
        targetPort: 9999
        name: tcp

phpmyadmin:
  containers:
    - name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - containerPort: 8015
  envs:
    secret:
      - phpmyadmin-secret
      - db-secret
    configs:
      PMA_PORT: 3306
      PMA_HOST: lineblocs.ckehyurhpc6m.ca-central-1.rds.amazonaws.com
  service:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 8015

routeeditor:
  containers:
    - name: call-route-editor
      image: lineblocs/call-route-editor:master
      ports:
        - containerPort: 8005
  domain: route.
  service:
    ports:
      - port: 80
        targetPort: 8005

tsbindings:
  containers:
    - name: tsbindings
      image: lineblocs/ts-bindings:master
      ports:
        - containerPort: 8080
  domain: tsc.
  service:
    ports:
      - port: 80
        targetPort: 8080
